benchmarks:
- vorbis-2017-12-11
- freetype2-2017
- libjpeg-turbo-07-2017
- curl_curl_fuzzer_http
concurrent_builds: 2
description: null
docker_registry: gcr.io/fuzzbench
experiment: exp-2022-06-06-00-44-39
experiment_filestore: /home/b/tmp/ast-fuzz/experiment-data
fuzzers:
- afl_from_input_seed
git_hash: c4eff492acf7ef4c19ca6ee405c3c771c06d4667
local_experiment: true
max_total_time: 7200
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/b/tmp/ast-fuzz/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 3
