benchmarks:
- libpng-1.2.56
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: exp-2022-04-22-00-58-08
experiment_filestore: /home/b/tmp/ast-fuzz/experiment-data
fuzzers:
- aflplusplus_ast_o0
- aflplusplus_ast_o1
- aflplusplus_ast_o2
- aflplusplus_ast_o3
git_hash: 23b47148183fae6cbfcdf65c698dffe01fe3d532
local_experiment: true
max_total_time: 14400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/b/tmp/ast-fuzz/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 3
