benchmarks:
- freetype2-2017
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: exp-2022-04-19-22-48-43
experiment_filestore: /home/b/tmp/ast-fuzz/experiment-data
fuzzers:
- aflo0
git_hash: 813457d2d6c0ab52f042654e03272bc74cf51ef3
local_experiment: true
max_total_time: 5400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/b/tmp/ast-fuzz/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 3
