benchmarks:
- libhtp_fuzz_htp
concurrent_builds: 1
description: null
docker_registry: gcr.io/fuzzbench
experiment: exp-2022-05-27-17-00-11
experiment_filestore: /home/b/tmp/ast-fuzz/experiment-data
fuzzers:
- aflplusplus_ast_f0
- aflplusplus_ast_f1
git_hash: da85d2eb25be99b08f26010a637a4c9ec3035283
local_experiment: true
max_total_time: 180
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/b/tmp/ast-fuzz/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 3
