benchmarks:
- woff2-2016-05-06
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: woff2-2016-05-06-all
experiment_filestore: /home/matt/experiment-data
fuzzers:
- aflplusplus_ast_o0
- aflplusplus_ast_o1
- aflplusplus_ast_o2
- aflplusplus_ast_o3
git_hash: 23b47148183fae6cbfcdf65c698dffe01fe3d532
local_experiment: true
max_total_time: 14400
measurers_cpus: null
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
report_filestore: /home/matt/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
trials: 3
